# Generated by Django 4.0.6 on 2022-07-25 21:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import eruna.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Destination Name')),
                ('description', models.TextField(verbose_name='Destination Description')),
                ('location', models.CharField(max_length=256, verbose_name='Destination Location')),
                ('price', models.IntegerField(verbose_name='Cost of Vacation')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='Distance From Kampala')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('related_url', models.URLField(verbose_name='Url To Related Article')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload On')),
            ],
        ),
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Destination Name')),
                ('description', models.TextField(verbose_name='Destination Description')),
                ('location', models.CharField(max_length=256, verbose_name='Destination Location')),
                ('price', models.IntegerField(verbose_name='Cost of Vacation')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='Distance From Kampala')),
                ('room_count', models.IntegerField(verbose_name='Number of Rooms')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('related_url', models.URLField(verbose_name='Url To Related Article')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload On')),
            ],
        ),
        migrations.CreateModel(
            name='RentalCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Car Name')),
                ('reg_no', models.CharField(max_length=256, verbose_name='Car Registration Number')),
                ('owner', models.CharField(default='Admin', max_length=256, verbose_name='Car Owner')),
                ('seats', models.IntegerField(verbose_name='Number of Seats')),
                ('price', models.IntegerField(verbose_name='Cost of hire')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload On')),
            ],
        ),
        migrations.CreateModel(
            name='TravelMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=256, verbose_name='Destination Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
            ],
        ),
        migrations.CreateModel(
            name='TravelMomentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to=eruna.models.get_file_path, verbose_name='Image Url')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload On')),
                ('travel_moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruna.travelmoment')),
            ],
        ),
        migrations.CreateModel(
            name='LoungeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to=eruna.models.get_file_path, verbose_name='Image Url')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload On')),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruna.lounge')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to=eruna.models.get_file_path, verbose_name='Image Url')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload On')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruna.destination')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to=eruna.models.get_file_path, verbose_name='Image Url')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload On')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruna.rentalcar')),
            ],
        ),
    ]
