# Generated by Django 4.0.6 on 2022-07-25 22:04

from django.db import migrations, models
import eruna.models


class Migration(migrations.Migration):

    dependencies = [
        ('eruna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationimage',
            name='online_url',
            field=models.URLField(default='', verbose_name='Online Image Url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=eruna.models.get_file_path, verbose_name='Image Url'),
        ),
    ]
