# Generated by Django 4.0.6 on 2022-07-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruna', '0003_alter_destination_related_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lounge',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cost of Vacation'),
        ),
        migrations.AlterField(
            model_name='rentalcar',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cost of hire'),
        ),
    ]
