# Generated by Django 4.2.7 on 2023-11-18 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eruna", "0004_alter_lounge_price_alter_rentalcar_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loungeimage",
            name="lounge",
        ),
        migrations.RemoveField(
            model_name="travelmomentimage",
            name="travel_moment",
        ),
        migrations.DeleteModel(
            name="CarImage",
        ),
        migrations.DeleteModel(
            name="Lounge",
        ),
        migrations.DeleteModel(
            name="LoungeImage",
        ),
        migrations.DeleteModel(
            name="RentalCar",
        ),
        migrations.DeleteModel(
            name="TravelMoment",
        ),
        migrations.DeleteModel(
            name="TravelMomentImage",
        ),
    ]
