# Generated by Django 4.0.6 on 2022-07-26 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eruna', '0003_alter_destination_related_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='User Id')),
                ('mode_of_payment', models.CharField(max_length=256, verbose_name='Mode of Payment')),
                ('total_amount_paid', models.IntegerField(verbose_name='Total Amount Paid')),
                ('email', models.CharField(max_length=256, verbose_name="Client's Email")),
                ('country_code', models.CharField(max_length=9, verbose_name="Client's Country")),
                ('address', models.CharField(max_length=256, verbose_name="Client's Address")),
                ('order_key', models.CharField(max_length=256, verbose_name='Order key')),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Paid On')),
            ],
        ),
        migrations.CreateModel(
            name='VacationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default='1', verbose_name='User Id')),
                ('total_price', models.IntegerField(verbose_name='Total Price')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Vacation is complete')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Upload On')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruna.destination')),
                ('payment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.payment')),
            ],
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default='1', verbose_name='User Id')),
                ('total_price', models.IntegerField(verbose_name='Total Price')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_return', models.BooleanField(default=False, verbose_name='Car is returned')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Upload On')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruna.rentalcar')),
                ('payment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.payment')),
            ],
        ),
    ]
