# Generated by Django 4.0.6 on 2022-07-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_user_payment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Amount Paid'),
        ),
        migrations.AlterField(
            model_name='vacationbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Price'),
        ),
    ]
