# Generated by Django 4.0.6 on 2022-07-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_carbooking_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbooking',
            old_name='user',
            new_name='user_id',
        ),
    ]
