# Generated by Django 4.0.6 on 2022-07-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_user_carbooking_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbooking',
            old_name='is_return',
            new_name='is_returned',
        ),
    ]
