# Generated by Django 4.2.7 on 2023-11-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_rename_is_return_carbooking_is_returned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carbooking",
            name="payment_id",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.payment",
            ),
        ),
    ]
